addons:
  apt:
    packages:
      - libboost-dev

sudo: false

install:
  - wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run -O cuda9.run
  - chmod +x cuda9.run
  - ./cuda9.run --silent --toolkit --toolkitpath=`pwd`/cuda-9.0

script:
  - ln -s Makefile.config.travis Makefile.config
  - make CUDA_ROOT=cuda-9.0
  - export DATE=`date +%Y%m%d`
  - echo $DATE
  - mkdir -p latest
  - cp lib/libcprof.so latest/libcprof.so

deploy:
  provider: gcs
  access_key_id: GOOGEQY5LDVKHTFZ6AQJ 	
  secret_access_key:
    secure: aY6WZbH5VZTaHCmkMW1Wic9IeLYyso//B/fTcPcVGJHbivKMcSwELsS5/OgKG6H30rNAMdRu7RxfR35v42oT5BDOs7IdPNOd8mcTvU401tbx+6DFqExLe4O2dkp6CLcazv/4JEoTOuLxBpj9Xo/el9a+v9e9Dwti6WusYyDcHXbgwVC4RXB1LiW2sDJ9Whj6hM7z0fSlkvFco8CZPFr4IQd18QGBSo2Cut4WcnMuN4dOo76YV4MsOkvMxv18/G9ACw4aRp/K47ZF5ALbIhN6676XyqqPaghmYgpO4m9CSYiXcWX0g4A9weZzK5WBqdMKDe2zsyznha4guHc4OMsPoQgocG+PwbxGHFn1ElG2GjQxAwzhKEmGu3CbyXJjvY7cbNUiU7ZKWxkuy4RrcuSlcDNgxXazLIpFaKq5o72EO5DA6XNodigEFiV5/w0fwuqKrKKWR2xvlkF0ujvWYkdEhYhD1EmDLrf0VAAd2oj/qx6LZnZReqHbSRa871SJNJv0/raPBhy23L9uAbKu8R2SAmRUvDnl5KiDyhpN7cZFoRzkXoOMwf8xFl+odNVhTt6tC8f870YBfmrEHW7ydWiFVddYeXg2ULr8ayyu83zps8RXFKzQgzjeGXNbC6+7i2NYXPTYqx4loFIN5UQsu0m//fYX0SuYUK+5XYehbS1gkA8=
  bucket: cprof
  skip_cleanup: true
  local_dir: latest
  on:
    all_branches: true
