# BOOST_ROOT=$(HOME)/software/boost_1_65_1

CUDA_ROOT ?= /usr/local/cuda

OPENTRACING_INCLUDE = $(HOME)/software/opentracing-cpp/include
OPENTRACING_LIB     = $(HOME)/software/opentracing-cpp/lib

ZIPKIN_OPENTRACING_INCLUDE = $(HOME)/software/zipkin-cpp-opentracing/include
ZIPKIN_OPENTRACING_LIB     = $(HOME)/software/zipkin-cpp-opentracing/lib

# Debug or Release
BUILD_TYPE ?= Debug